/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_weakie_share_jni_SendData */

#ifndef _Included_com_weakie_share_jni_SendData
#define _Included_com_weakie_share_jni_SendData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_weakie_share_jni_SendData
 * Method:    initCOM
 * Signature: (Lcom/weakie/share/jni/SendData/PtrData;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_weakie_share_jni_SendData_initCOM
  (JNIEnv *, jclass, jobject, jstring port);

/*
 * Class:     com_weakie_share_jni_SendData
 * Method:    sendData
 * Signature: (Lcom/weakie/share/jni/SendData/PtrData;[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_weakie_share_jni_SendData_sendData
  (JNIEnv *, jclass, jobject, jbyteArray, jint);

/*
 * Class:     com_weakie_share_jni_SendData
 * Method:    destroy
 * Signature: (Lcom/weakie/share/jni/SendData/PtrData;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_weakie_share_jni_SendData_destroy
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_weakie_share_jni_SendData
 * Method:    formatData
 * Signature: (IIIIII[B)V
 */
JNIEXPORT jint JNICALL Java_com_weakie_share_jni_SendData_formatPointData
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jbyteArray);

JNIEXPORT jint JNICALL Java_com_weakie_share_jni_SendData_formatIniWeldParaData
(JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
