/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_weakie_jni_SendData */

#ifndef _Included_com_weakie_jni_SendData
#define _Included_com_weakie_jni_SendData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_weakie_jni_SendData
 * Method:    initCOM
 * Signature: (Lcom/weakie/jni/SendData/PtrData;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_weakie_jni_SendData_initCOM
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_weakie_jni_SendData
 * Method:    sendData
 * Signature: (Lcom/weakie/jni/SendData/PtrData;[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_weakie_jni_SendData_sendData
  (JNIEnv *, jclass, jobject, jbyteArray);

/*
 * Class:     com_weakie_jni_SendData
 * Method:    formatData
 * Signature: (IIIIII[B)V
 */
JNIEXPORT void JNICALL Java_com_weakie_jni_SendData_formatData
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
