/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_weakie_jni_SendData_PtrData */

#ifndef _Included_com_weakie_jni_SendData_PtrData
#define _Included_com_weakie_jni_SendData_PtrData
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
